- js/build.js
Fixes https://github.com/Fliplet/fliplet-studio/issues/1326
> Updates support for arrays in data summary

- js/build.js
- beforeQueryChart
- afterQueryChart
- data_point_interact
- legend_filter
> Hooks + GA

- build.html
- css/build.css
- interface.html
- js/build.js
- js/interface.js
See https://github.com/Fliplet/fliplet-widget-chart-bar/pull/5
> Allows users to customize chart heights for mobile and tablet/desktop

- js/build.js
Changes the default colours to match the new colours in the new theme.
> Updates chart's default colors

- build.html
- interface.html
- js/build.js
- js/interface.js
- widget.json
- We removed the height settings from the component as users will be able to change that via the new appearance settings
- The version bump is so that users that already are using that settings keep their chart with the correct height
This should only be merged once the new Appearance settings are ready for production
> Removed height settings and version bump

- js/build.js
- Adds a Hook handler to reconfigure the Chart after the styles are changes in the Appearance settings
> Styles changed hook

- interface.html
@tonytlwu @squallstar 
Fliplet/fliplet-studio#4911
Added link on "Need help" button.
> Clicking on "Need help" now leads to Fliplet documentation "How to Configure Charts"

- js/build.js
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5529
Make use of the new hook added in https://github.com/Fliplet/fliplet-api/pull/3793
> Use new appearance hook

- js/build.js
Follows https://github.com/Fliplet/fliplet-widget-chart-donut/pull/18
> Ensures chart instance is made available after render

- js/build.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/5615
> Start autorefresh when initial data fetch fails

- js/build.js
https://github.com/Fliplet/fliplet-studio/issues/5477
Allow users to dynamically change chart colors.
https://share.getcloudapp.com/geuWQbNn
@upplabs-alex-levchenko
> [Fix] Allow users to dynamically change chart colors.

- js/build.js
https://github.com/Fliplet/fliplet-studio/issues/5477
Allow users to dynamically change chart colors.
https://share.getcloudapp.com/geuWQbNn
@upplabs-alex-levchenko
> [Fix] Allow users to dynamically change chart colors. For production.

- js/interface.js
OD-16 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-16
Chart Donut
Pass new variable for the default name into DS Provider
https://screencast-o-matic.com/watch/cY63Xp7PE2
@upplabs-alex-levchenko @YaroslavOvdii
> OD-16 [Feature] Integration new default variable into Donut Chart

- js/interface.js
OD-218 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-218
Fix to bug with security rules alert
@upplabs-alex-levchenko @YaroslavOvdii
> OD-218 [Fix] Added access rules to Chart Donut

- widget.json
Ref. https://weboo.atlassian.net/browse/ID-290
Requires Fliplet/fliplet-studio#7074
> ID-290 [Maintenance] Ensures apps on the new theme don't see settings related to the old theme

- build.html
- js/build.js
https://weboo.atlassian.net/browse/OD-96
Color inheritance will be working correctly in the Chart components.
https://share.getcloudapp.com/GGu282mR
@upplabs-alex-levchenko
> OD-96 [Feature] Color inheritance will be working correctly in the Chart components.

- js/build.js
Ref. https://weboo.atlassian.net/browse/ID-1949
> ID-1949 [Fix] Ensures Fliplet.Chart.get() works on load

- build.html
- js/build.js
- translation.json
Ref. https://weboo.atlassian.net/browse/ID-1516
> ID-1516 [Feat] Localize translations, date and number formats

- js/build.js
- fliplet-widget-chart-donut
Set selection of data point/a segment 
Default false
Set Whether to display a slice offset from the center.
Default false
[XOR-57](https://weboo.atlassian.net/browse/XOR-57)
- None
- None
- None
None
> XOR-57 [Fix] Stop highlighting the first slice in donut chart

- js/build.js
Ref. https://weboo.atlassian.net/browse/OD-850
> OD-850 [Fix] Wait for framework initialization before initializing chart

- js/build.js
- widget.json
Requires https://github.com/Fliplet/fliplet-api/pull/5413
Ref. https://weboo.atlassian.net/browse/OD-850
> OD-850 [Fix] Use fliplet-chart to manage global settings

- build.html
- interface.html
- js/build.js
- translation.json
- widget.json
| PR | Merged by |
| -- | --------- |
| #41 OD-787 [Fix] Fixed title |  @OleksandrLavrynenko |
| #37 ID-1516 [Feat] Localize translations, date and number formats |  @tonytlwu |
| #40 XOR-57 [Fix] Stop highlighting the first slice in donut chart |  @tonytlwu |
| #43 OD-850 [Fix] Wait for framework initialization before initializing chart |  @tonytlwu |
| #44 OD-850 [Fix] Use fliplet-chart to manage global settings |  @tonytlwu |
> Release to Production
